### ISSUE TITLE
Meanings of some translations

### ISSUE THREAD

**Issue by raiseandfall** [discogs/discogs-i18n#56]
Hey guys,

I'm currently working on the french translations (messages.po).
I'm running into some trouble with one translation :
```ruby
msgid "Banned %s and deleted %d groups:"
```

Can you tell me kind of variable will be used for %s and %d ?
I can tell it will be strings but will it be the username or something else ? 
Ex : "Banned Foo and deleted Foo groups:" ( Foo being a username )
I'm trying to get the meaning of the sentence.

Also FYI there are a couple of entries that are duplicated, for example the following is there twice :
```ruby
msgid ""
"At this time, if you have paid for the order, we strongly encourage you "
"to\n"
"contact your payment method provider (PayPal, credit card, etc) to file a"
"\n"
"refund request. If you have not paid for the order, simply leave a "
"message on\n"
"the order page that you wish to cancel."
```
Not really a big deal but it could reduce the file size.

Thanks

**Comment by antolen** [comment]
%s is a username string
%d is the number of groups

Thanks for letting us know, the translation text is generated automatically, and it's common that whitespace would create two different strings. When translation is loaded, they are treated as different strings and each would need a translation. We try to limit those but some still slip through. I would suggest on creating translation for each string for now.

Let us know if you have any question about translations.

**Comment by raiseandfall** [comment]
Thanks for the clarification.
Yeah I had the same think going on with Django in the past.
I'm filling every entry for now.

Can you tell me what's the context of the sentence ?
Is it displayed once the user has been banned and x number of groups have been deleted ?
Or is displayed as a confirmation before the ban ? Like "Banned Foo and deleted 4 groups: Yes or No"
I'm asking since there's a colon at the end, which is a bit confusing.

Thanks

**Comment by antolen** [comment]
This sentence is shown **after** banning a spam user account.
After the colon there is a list of group topics that the user have created. 
It looks like:
``` 
Banned Foo and deleted 4 topics: 
- Topic A
- Topic B
- Topic C 
```

Thank you!

**Comment by raiseandfall** [comment]
Thanks ! 
I'm closing the issue for now.
