### ISSUE TITLE
Currencies in localization

### ISSUE THREAD

**Issue by raiseandfall** [discogs/discogs-i18n#57]
Hi guys,

Some localizations contain a dollar price / sign. For example :
```python
msgid ""
"e.g. $5 for one item, $2 for each additional item, buyer pays shipping. "
"Additional shipping for nondomestic."
```

Not sure how you are working around that. Are you switching currencies with the languages ? Or are we just using the dollar for all languages ( as long as it's 'static', like above ).

I know there's a currency setting in the profile settings ( Default Currency Display ), are you using that ? If so, should the dollar sign in the localizations be a variable ?

Let me know, thanks ! 
I'll keep the dollar sign for now.

**Comment by deleteme** [comment]
Hi raiseandfall,

For this particular string, feel free to rewrite the translation to use the currency that's appropriate for the language. You don't have to keep the dollar sign if there is a better one for the language.

Most prices on the site will use a localized currency symbol and punctuation, however, there may be other strings that aren't formatted to use it. If you encounter any, let us know, and we can fix the original `msgid` string.

**Comment by raiseandfall** [comment]
@deleteme Thanks, will do.
