### ISSUE TITLE
Order of words in french

### ISSUE THREAD

**Issue by raiseandfall** [discogs/discogs-i18n#58]
There's a minor issue with one time localization for the french version :
```msgid "ago"```

It's a common issue on localized website. Let's say you have the following in english : 
```30 minutes ago```
The translation in french will be :
```il y a 30 minutes```
The ```ago``` moves in the beginning of the expression. 

If you are using this translation for this kind of expression, we are gonna need to include the time as a parameter of the translation, otherwise facing bizarre sentences ( ```ago 30 minutes``` basically ).

Let me know your thoughts on that.

**Comment by deleteme** [comment]
Hi raiseandfall,

For that particular `msgid "ago"` string, it's only used in one place ([on this page](http://www.discogs.com/sell?mode=file)), and in the context you describe. That string is not very important to get translated.

We will probably replace it in the future with one that has more context, like "30 minutes ago". We do have a function that returns a "30 minutes ago" type of phrase, but it only supports English right now. We'd like to improve this so it can be localized.

**Comment by raiseandfall** [comment]
@deleteme Thanks for the explanation, I'll leave it like that for now ( filled with regular translation ).

Another small thing : I ran into a message ID who does not make sense in terms of HTML tags : 
```python
msgid ""
"Cookies are not enabled.<p>You do not have cookies enabled on your "
"browser. Please refer to the Help section of your browser for "
"instructions on enabling cookies.<p>** <b>After</b> you have enabled "
"cookies please %s to log in. **"
```
The closing tag of the paragraph is actually an open tag, not a huge deal but it might break on certain browsers. I just wanted to let you know in case the actual message string in english has the same.

**Comment by deleteme** [comment]
Hi raiseandfall,

Good catch! We can fix the markup soon.

**Comment by raiseandfall** [comment]
Awesome thanks.
Hey I just saw that you pushed a lot of french translations from contracted translators. When are you planning on merging with master ? I want to see if I have to keep working on message.po on my current branch or not. 
Thanks !

**Comment by deleteme** [comment]
Yeah sorry about that. I plan on merging #59 onto master today. It should help a lot, but there's still more to do. When I compile the `messages.po` file, I see a report that it's 94% translated. We're also adding more strings to `message_js.po`.

**Comment by raiseandfall** [comment]
No worries.
I'll do a pull once it's on master.
Are they still working on the remaining 6% ? I might have already translated some of them, which hopefully can help wrap up the french part.

**Comment by deleteme** [comment]
#59 is merged, but I still have some more new strings to add (and some to remove), so the messages.po and messages_js.po files will be changing a little more. The contractors may continue to finish the remaining untranslated strings, but I'm not sure. You're welcome to provide any improvements to the new translations. Also, I tried preserving your translations, but a few may have been lost or overwritten.

**Comment by raiseandfall** [comment]
Thanks for the update ! I probably won't be able to work on it until a couple of days, so I'll just go along with what's merged on master.

**Comment by raiseandfall** [comment]
Closing this since issue got fixed ( missing closing tag ).
