### ISSUE TITLE
Localization current completion/status

### ISSUE THREAD

**Issue by raiseandfall** [discogs/discogs-i18n#66]
Hey guys,

I know you have a tool you run to get the completion in percentage for every language.
Wouldn't it be cool to have the current status / completion in the main readme markdown ? I'm thinking of something like : 

__French__
__Completion__: 45%
__Status__: currently being translated by contractor

That would definitely help us, especially for the main big files that require quite some time to translate. Knowing that a professional contractor is working on it might save us some time.

Let me know your thoughts. 
Thanks !

**Comment by weetzie** [comment]
Hi,

Thanks for the feedback!  Great idea!

Adding an exact completion percentage might be a challenge as it will be changing so frequently, however perhaps an estimate will work (example: 95%-100% translated).

I will add an update to the Readme file ASAP about what languages our contractors are currently working on.  

It's also worth mentioning that we welcome improvements to existing translations.  There are certainly many words and phrases that are a challenge to translate unless you are familiar with using Discogs.

We really appreciate all the work you have done so far!

**Comment by raiseandfall** [comment]
Hi @weetzie 

Thanks for the fast answer.
Awesome, I think an estimate is totally reasonable. 

Always welcome to help !

**Comment by weetzie** [comment]
Hi @raiseandfall ,

Thanks again for your feedback, and sorry that it has taken me so long to follow-up!  Our team has been investigating new ways to handle translations, and we have decided to move to a translation platform.  We have decided to move forward with Transifex, which will provide translators with a exact translation status for each language.

**Comment by raiseandfall** [comment]
Hi @weetzie 

Does that mean that you won't be supporting the translation on Github anymore and move to the Transifex platform ? Or does that mean that we can still contribute and you'll have translation statuses pulled from Transifex to Github ?
Thank you

**Comment by weetzie** [comment]
We plan to move entirely to Transifex in the future. However, if you are already in the middle of translation work here, our dev team can work on integrating your GitHub translations once they are received, as we realize we didn't provide a warning.  If you are still interesting is helping with translations, we do still plan to accept community translations. We will be posting more information soon.

**Comment by raiseandfall** [comment]
Thanks for your answer.
I was planning on starting another round of french translation in the next weeks, after pulling all that has been done in the last months in order to fix potential typos/mistakes. 
Since you guys are fully moving platform I don't think I'll start it, but I'll gladly be part of the community translation program to keep working on it.
