### ISSUE TITLE
German T-V distinction?

### ISSUE THREAD

**Issue by Fleshgrinder** [discogs/discogs-i18n#78]
I guess you guys are not aware of this, but in German we have a [T-V distinction](https://en.wikipedia.org/wiki/T%E2%80%93V_distinction) and you should decide how this should be handled. There are basically two different honorifics: **Du/du** and **Sie/sie**. You can read more about their meaning in the [German section in the T-V distinction article](https://en.wikipedia.org/wiki/T%E2%80%93V_distinction#German).

Personally I prefer **Du/du** over **Sie/sie**, but I am from Austria and I know that many people from (especially northern) Germany prefer **Sie/sie**. This is an important decision for your German speaking users and has a high impact on how they will perceive Discogs. You should not take this decision lightly, especially since German markets are always important.

Many websites (e.g. Wikipedia and most forum software) offer both forms to their users and let them choose what they prefer. This could be a possibility for Discogs as well. In this case I would suggest to use **Sie/sie** as default and allow users to switch to **Du/du**.

I plan to contribute some German translations, but this has to be decided upon before everything can be translated.

**Comment by weetzie** [comment]
Thanks for checking in with us!  We have discussed this issue in the past, but never made a final decision.  After further discussion and research, we are in agreement with you. Let's use Sie/sie as default.  

Currently we won't be able to offer users the option to switch between honorifics, but that's an interesting idea that perhaps we can consider in the future.  Thanks in advance for volunteering to contribute German translations!

**Comment by Fleshgrinder** [comment]
Great, then this is decided for now. :+1:
